version: "3"

services:
  db_book:
    build:
      context: ./
    container_name: db_book_dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGPASSWORD=admin
      - POSTGRES_DB=db_book_dev
      - DATABASE_HOST=localhost
    restart: always

volumes:
  db-data:
