create table accounts (
    no serial not null,
    email varchar primary key not null,
    email_confirm varchar not null,
    id_user varchar,
    user_type integer,
    last_name varchar,
    first_name varchar,
    last_name_kana varchar,
    first_name_kana varchar,
    birthday varchar,
    gender integer,
    tel varchar,
    zip varchar,
    prefecture varchar,
    city varchar,
    address3 varchar,
    building varchar,
    purpose integer,
    magazine bool,
    agree_to_terms bool
);