create table stories (
    no serial not null,
    id_user varchar not null,
    id_story varchar not null primary key,
    title_main varchar not null,
    auther_name varchar not null,
    is_complete bool not null,
    genre integer not null,
    catch_copy varchar not null,
    synopsis varchar not null,
    keywords varchar,
    extreme_depiction varchar not null,
    color_type integer not null,
    accept_advertisement bool not null,
    accept_rating bool not null,
    accept_reviews bool not null,
    accept_impression bool not null,
    publish_evaluation bool not null,
    accept_typo_reports bool not null
);