create table master_book (
    no serial not null,
    id_book varchar primary key not null,
    no_title integer,
    name_book varchar not null,
    genre integer,
    name_genre varchar,
    name_category varchar,
    is_complete bool,
    is_latest bool,
    is_reserve bool,
    id_series varchar,
    name_series varchar,
    price_unit varchar,
    price_now integer,
    book_detail varchar,
    point_id varchar,
    point integer,
    id_author varchar,
    id_publisher varchar,
    id_shop varchar,
    url_detail varchar,
    url_img varchar,
    url_img_t varchar,
    url_reader varchar,
    date_register varchar,
    date_sales varchar,
    label_free integer,
    label_free_s integer,
    label_disc integer,
    label_disc_s integer,
    label_new integer,
    label_off integer,
    label_complete_s integer
);