create table master_book
(
    no serial not null,
    id_book varchar primary key not null,
    name_book varchar not null,
    genre integer,
    is_complete bool,
    series_id varchar,
    name_series varchar,
    price_unit varchar,
    price_now integer,
    detail varchar,
    point_id varchar,
    point integer,
    id_auther varchar,
    id_publisher varchar,
    id_shop varchar,
    url_img varchar,
    url_img_t varchar,
    date_register varchar,
    date_sales varchar,
    label_free integer,
    label_free_s integer,
    label_disc integer,
    label_disc_s integer,
    label_new integer,
    label_off integer,
    label_complete_s integer
);

insert into master_book
    (
    id_book,
    name_book,
    genre,
    is_complete,
    series_id,
    name_series,
    price_unit,
    price_now,
    detail,
    point_id,
    point,
    id_auther,
    id_publisher,
    id_shop,
    url_img,
    url_img_t,
    date_register,
    date_sales,
    label_free,
    label_free_s,
    label_disc,
    label_disc_s,
    label_new,
    label_off,
    label_complete_s
    )
values
    (
    'bl12345',
    'ドラゴンボール',
    1,
    true,
    'bt34a',
    'ドラゴンボール',
    367,
    250,
    '世界中に散らばった七つの球をすべて集めると、どんな願いも一つだけ叶えられるという秘宝・ドラゴンボールと、主人公・孫悟空（そん・ごくう）を中心に展開する「冒険」「夢」「バトル」「友情」などを描いた長編漫画。『週刊少年ジャンプ』（集英社）にて1984年（昭和59年）51号から1995年（平成7年）25号までの約10年半にわたって連載。各話数の通し番号は「其之○○」となっており、数字は漢数字で表される。このほかに番外編『TRUNKS THE STORY -たったひとりの戦士-』も掲載された。1986年（昭和61年）からフジテレビ系列でテレビアニメ『ドラゴンボール』、『ドラゴンボールZ』が約11年間放送され、平均視聴率20%以上を維持し[1]、全世界80ヵ国以上で放送された',
    'gogo_15677',
    14,
    'tdn44567',
    'mag0001',
    'oxd56749',
    'https://www.google.com/?hl=ja',
    'https://www.yahoo.co.jp/',
    '2019-11-21',
    '2019-09-31',
    0,
    1,
    0,
    0,
    1,
    25,
    1
);
